version: '3.8'

services: 
  postgres:
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
    ports:
      - $DB_LOCAL_PORT:$DB_PORT
    volumes: 
      - db-data:/var/lib/postgresql/data
      - ./db/backup/files/:/data_backup/data

volumes: 
  db-data: