version: '3.8'

services: 
  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
    ports:
      - $DB_LOCAL_PORT:$DB_PORT
    volumes: 
      - db-data:/var/lib/postgresql/data
      - ./db/backup/files/:/data_backup/data
  pgadmin: 
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$DB_PASSWORD
    ports: 
      - $PGADMIN_PORT:$PGADMIN_PORT_LOCAL

volumes: 
  db-data:
