name: Build and deploy to Production

on:
  push:
    branches:
      - develop

jobs:
  docker: 
    name: Build and push on DockerHub
    runs-on: ubuntu-latest
    steps: 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/decon-api:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy_to_production:
    name: Deploy to Production
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change Dockerfile
        run: mv ./secondDocker Dockerfile
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "deconcesionarias-api" #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true